version: "3"
services:
  nginx:
    image: nginx:alpine
    deploy:
      replicas: 5
  ubuntu:
    image: ubuntu:latest
    command: ["bash", "-c", "apt-get update && apt-get install -y curl && while true; do curl -s -o
/dev/null http://nginx; sleep 1; done"]

    deploy:
      replicas: 5

    depends_on:
      - nginx